definitions:
  auth.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  auth.LoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
    type: object
  auth.RegisterRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
      username:
        example: john_doe
        type: string
    type: object
  auth.ResendConfirmationRequest:
    properties:
      email:
        type: string
    type: object
  photo.Photo:
    properties:
      created_at:
        description: Дата и время создания фото
        type: string
      description:
        description: Описание изображения
        type: string
      id:
        description: Идентификатор фото
        type: integer
      image_url:
        description: URL изображения
        type: string
      user_id:
        description: Идентификатор пользователя, загрузившего фото
        type: integer
    type: object
info:
  contact: {}
paths:
  /confirm:
    get:
      consumes:
      - application/json
      description: Подтверждает email пользователя на основе предоставленного токена.
      parameters:
      - description: Токен подтверждения
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Email успешно подтверждён!
          schema:
            type: string
        "400":
          description: Token is missing
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "401":
          description: Invalid or expired token
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "500":
          description: Failed to activate user
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
      summary: Подтверждение email пользователя
      tags:
      - auth
  /login:
    post:
      consumes:
      - application/json
      description: Этот эндпоинт позволяет пользователю авторизоваться, используя
        email и пароль.
      parameters:
      - description: Данные для входа пользователя
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: token" "Токен успешно создан
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Некорректные данные
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "401":
          description: Неверные учетные данные
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
      summary: Авторизация пользователя
      tags:
      - auth
  /photos/{id}:
    get:
      description: Fetch photo details by its unique identifier.
      parameters:
      - description: ID of the photo to retrieve
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Returns the photo details including the full URL
          schema:
            $ref: '#/definitions/photo.Photo'
        "400":
          description: Invalid photo ID
          schema:
            type: string
        "404":
          description: Photo not found
          schema:
            type: string
      summary: Retrieves a photo by ID
      tags:
      - Photos
  /photos/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload a photo with an optional description. The uploaded photo
        is associated with the authenticated user.
      parameters:
      - description: Photo file to upload
        in: formData
        name: photo
        required: true
        type: file
      - description: Description for the photo
        in: formData
        name: Description
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Returns the uploaded photo details including the generated
            URL
          schema:
            $ref: '#/definitions/photo.Photo'
        "400":
          description: Error uploading file or invalid input
          schema:
            type: string
        "401":
          description: Unauthorized access
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Uploads a new photo
      tags:
      - Photos
  /register:
    post:
      consumes:
      - application/json
      description: Этот эндпоинт позволяет зарегистрировать нового пользователя, используя
        email, имя пользователя и пароль.
      parameters:
      - description: Данные для регистрации пользователя
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: message" "Registration successful! Please check your email
            to confirm.
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Некорректные данные
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "500":
          description: Ошибка регистрации
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
      summary: Регистрация нового пользователя
      tags:
      - auth
  /resend-confirmation:
    post:
      consumes:
      - application/json
      description: Этот эндпоинт позволяет повторно отправить письмо для подтверждения
        почты.
      parameters:
      - description: Email для повторной отправки подтверждения
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.ResendConfirmationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Письмо с подтверждением отправлено повторно
          schema:
            type: string
        "400":
          description: Некорректные данные
          schema:
            type: string
        "404":
          description: Пользователь не найден
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Повторная отправка письма с подтверждением
      tags:
      - auth
swagger: "2.0"
