basePath: /
definitions:
  InstaSpace_internal_auth.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  InstaSpace_internal_auth.LoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
    type: object
  InstaSpace_internal_auth.RegisterRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
      username:
        example: john_doe
        type: string
    type: object
  InstaSpace_internal_auth.ResendConfirmationRequest:
    properties:
      email:
        type: string
    type: object
  internal_auth.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  internal_auth.LoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
    type: object
  internal_auth.RegisterRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
      username:
        example: john_doe
        type: string
    type: object
  internal_auth.ResendConfirmationRequest:
    properties:
      email:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: ramaro@internet.ru
    name: Техническая поддержка
  description: Документация для API InstaSpace, включающая функционал авторизации
    и регистрации.
  title: Insta Space API
  version: "1.0"
paths:
  /confirm:
    get:
      consumes:
      - application/json
      description: Подтверждает email пользователя на основе предоставленного токена.
      parameters:
      - description: Токен подтверждения
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Email успешно подтверждён!
          schema:
            type: string
        "400":
          description: Token is missing
          schema:
            $ref: '#/definitions/internal_auth.ErrorResponse'
        "401":
          description: Invalid or expired token
          schema:
            $ref: '#/definitions/internal_auth.ErrorResponse'
        "500":
          description: Failed to activate user
          schema:
            $ref: '#/definitions/internal_auth.ErrorResponse'
      summary: Подтверждение email пользователя
      tags:
      - auth
  /generate-token:
    get:
      consumes:
      - application/json
      description: Генерирует новый JWT токен, используя переданный email в качестве
        данных. Токен будет действителен в течение 24 часов.
      parameters:
      - description: Email для включения в JWT токен
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Успешно сгенерированный JWT токен
          schema:
            type: string
      summary: Генерация JWT токена
      tags:
      - auth
  /login:
    post:
      consumes:
      - application/json
      description: Этот эндпоинт позволяет пользователю авторизоваться, используя
        email и пароль.
      parameters:
      - description: Данные для входа пользователя
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: token" "Токен успешно создан
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Некорректные данные
          schema:
            $ref: '#/definitions/internal_auth.ErrorResponse'
        "401":
          description: Неверные учетные данные
          schema:
            $ref: '#/definitions/internal_auth.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/internal_auth.ErrorResponse'
      summary: Авторизация пользователя
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Этот эндпоинт позволяет зарегистрировать нового пользователя, используя
        email, имя пользователя и пароль.
      parameters:
      - description: Данные для регистрации пользователя
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: message" "Registration successful! Please check your email
            to confirm.
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Некорректные данные
          schema:
            $ref: '#/definitions/internal_auth.ErrorResponse'
        "500":
          description: Ошибка регистрации
          schema:
            $ref: '#/definitions/internal_auth.ErrorResponse'
      summary: Регистрация нового пользователя
      tags:
      - auth
  /resend-confirmation:
    post:
      consumes:
      - application/json
      description: Этот эндпоинт позволяет повторно отправить письмо для подтверждения
        почты.
      parameters:
      - description: Email для повторной отправки подтверждения
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_auth.ResendConfirmationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Письмо с подтверждением отправлено повторно
          schema:
            type: string
        "400":
          description: Некорректные данные
          schema:
            type: string
        "404":
          description: Пользователь не найден
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Повторная отправка письма с подтверждением
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
